syntax = "Lua54"
column_width = 120
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferDouble"
space_after_function_names = "Never"
line_endings = "Unix"
call_parentheses = "Always"
collapse_simple_statement = "Always"
sort_requires = { enabled = true }
